name: 'helllicht/rsync'
description: 'helllicht rsync action'
inputs:
  remote_server:
    description: 'Host to deploy on'
    required: true
  remote_port:
    description: 'Port to use for connection'
    required: false
  remote_user:
    description: 'User to use for connection'
    required: true
  local_directory:
    description: 'Local directory to be synced'
    required: true
  remote_directory:
    description: 'Target directory on the host system'
    required: true
  dry_run:
    description: 'Perform a dry run instead of actually syncing files'
    required: true
  delete_from_remote_directory:
    description: 'Delete files from remote_dir, that are not in the local_dir'
    required: false
  exclude_file:
    description: 'path to a syncignore file'
    required: false
  remote_password:
    description: 'Password for the host system. Don`t set if authorizing by ssh key'
    required: false
  private_key:
    description: 'Private key to the public key on the host system. Don`t set if authorizing by password. When set, must equal the entire private key file - including begin-line and end-line'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Deploy
      env:
        REMOTE_USER: ${{ github.event.input.remote_user }}
        REMOTE_SERVER: ${{ github.event.input.remote_server }}
        REMOTE_PORT: ${{ github.event.input.remote_port }}
        LOCAL_DIRECTORY: ${{ github.event.input.local_directory }}
        REMOTE_DIRECTORY: ${{ github.event.input.remote_directory }}
        PRIVATE_KEY: ${{ github.event.input.private_key }}
        REMOTE_PASSWORD: ${{ github.event.input.remote_password }}
        DRY_RUN: ${{ github.event.input.dry_run }}
        EXCLUDE_FILE: ${{ github.event.input.exclude_file }}
        DELETE_FROM_REMOTE_DIRECTORY: ${{ github.event.input.delete_from_remote_directory }}

      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
