name: 'helllicht/rsync'
description: 'helllicht rsync action'
inputs:
  remote_server:
    description: 'Host to deploy on'
    required: true
  remote_port:
    description: 'Port to use for connection'
    required: false
  remote_user:
    description: 'User to use for connection'
    required: true
  local_directory:
    description: 'Local directory to be synced'
    required: true
  remote_directory:
    description: 'Target directory on the host system'
    required: true
  dry_run:
    description: 'Perform a dry run instead of actually syncing files'
    required: true
  delete_from_remote_directory:
    description: 'Delete files from remote_dir, that are not in the local_dir'
    required: false
  exclude_file:
    description: 'path to a syncignore file'
    required: false
  remote_password:
    description: 'Password for the host system. Don`t set if authorizing by ssh key'
    required: false
  private_key:
    description: 'Private key to the public key on the host system. Don`t set if authorizing by password. When set, must equal the entire private key file - including begin-line and end-line'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setting vars
      run: |
        echo "Setting up vars..."
        echo ""

        echo "REMOTE_SERVER=${{ inputs.remote_server }}" >> $GITHUB_ENV
        echo "REMOTE_PORT=${{ inputs.remote_port }}" >> $GITHUB_ENV
        echo "REMOTE_USER=${{ inputs.remote_user }}" >> $GITHUB_ENV
        echo "LOCAL_DIRECTORY=${{ inputs.local_directory }}" >> $GITHUB_ENV
        echo "REMOTE_DIRECTORY=${{ inputs.remote_directory }}" >> $GITHUB_ENV
        echo "DRY_RUN=${{ inputs.dry_run }}" >> $GITHUB_ENV
        echo "DELETE_FROM_REMOTE_DIRECTORY=${{ inputs.delete_from_remote_directory }}" >> $GITHUB_ENV
        echo "EXCLUDE_FILE=${{ inputs.exclude_file }}" >> $GITHUB_ENV

        if [ "${{ inputs.remote_password }}" != '' ]; then
          echo "REMOTE_PASSWORD=${{ inputs.remote_password }}" >> $GITHUB_ENV
        fi

        if [ "${{ inputs.private_key }}" != '' ]; then
          PRIVATE_KEY=${{ inputs.private_key }}
          PRIVATE_KEY="${PRIVATE_KEY//'%'/'%25'}"
          PRIVATE_KEY="${PRIVATE_KEY//$'\n'/'%0A'}"
          PRIVATE_KEY="${PRIVATE_KEY//$'\r'/'%0D'}"
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
        fi

        echo "Done."
        echo ""
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
